---
- name: Install strongswan custom facts
  become: yes
  copy: src=strongswan.fact
        dest=/etc/ansible/facts.d/strongswan.fact
        mode=0755

- name: Reload ansible local facts
  setup: filter=ansible_local

- name: Add strongswan PGP key
  shell: "gpg --recv-keys DF42C170B34DBA77"
  args:
    executable: /bin/bash
  when: not ansible_local.strongswan.strongswan_key_added

- name: Add networkmanager-strongswan PGP key
  shell: "gpg --recv-keys 765FE26C6B467584"
  args:
    executable: /bin/bash
  when: not ansible_local.strongswan.nm_strongswan_key_added

- name: Clone strongswan
  become: yes
  git:
    repo: https://aur.archlinux.org/strongswan.git
    dest: /usr/local/src/strongswan
    update: no

- name: Set user as owner
  become: yes
  file:
    path: /usr/local/src/strongswan
    recurse: yes
    owner: "{{ansible_env.USER}}"

- name: Add --enable-nm flag
  lineinfile:
     path: /usr/local/src/strongswan/PKGBUILD
     insertafter: "^ +./configure "
     line: "        --enable-nm \\"

- name: Install strongswan
  command: makepkg -si --noconfirm
  args:
    chdir: /usr/local/src/strongswan
  when: not ansible_local.strongswan.strongswan_installed

- name: Install strongswan plugin for NetworkManager
  yaourt:
    name: networkmanager-strongswan
    state: present
